apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: multi-tier-app
  labels:
    app: frontend
    tier: frontend
spec:
  selector:
    app: frontend
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: NodePort
